server:
  port: 10000
spring:
  application:
    name: ancientpower-provider
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
dubbo:
  scan:
    base-packages: io.jovi.ancientpower
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    timeout: 10000
  cloud:
    subscribed-services: