server:
  port: 8080
spring:
  application:
    name: ancientpower-provider
dubbo:
  scan:
    base-packages: io.jovi.ancientpower
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181
    timeout: 10000
