server:
  port: 10001
spring:
  application:
    name: ancientpower-consumer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
dubbo:
  scan:
    base-packages: io.jovi.ancientpower
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    timeout: 10000

